#[derive(Clone, Copy, PartialEq, Eq)]
pub enum ApiKind {
    Standard,
    Button,
    Card,
    Grid,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub struct ComponentCategory {
    pub index: &'static str,
    pub title: &'static str,
    pub description: &'static str,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub struct ComponentSpec {
    pub slug: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub description: &'static str,
    pub docs: &'static str,
    pub component_name: &'static str,
    pub class_name: &'static str,
    pub api_kind: ApiKind,
}

pub const CATEGORIES: &[ComponentCategory] = &[
    ComponentCategory {
        index: "01",
        title: "Actions",
        description: "Interactive controls for direct user actions and mode changes.",
    },
    ComponentCategory {
        index: "02",
        title: "Data Display",
        description: "Compact components for status, records, formatted content, and structured data.",
    },
    ComponentCategory {
        index: "03",
        title: "Data Entry",
        description: "Input controls for capture, selection, verification, and preference editing.",
    },
    ComponentCategory {
        index: "04",
        title: "Feedback",
        description: "Response surfaces for state, progress, warnings, and transient events.",
    },
    ComponentCategory {
        index: "05",
        title: "Layout",
        description: "Spacing, app structure, and responsive composition primitives.",
    },
    ComponentCategory {
        index: "06",
        title: "Navigation",
        description: "Route, hierarchy, progress, and page movement primitives.",
    },
    ComponentCategory {
        index: "07",
        title: "Surfaces",
        description: "Expandable, contextual, and mobile-first overlay containers.",
    },
];

pub const COMPONENTS: &[ComponentSpec] = &[
    ComponentSpec {
        slug: "button",
        name: "Button",
        category: "Actions",
        description: "Clickable buttons for actions.",
        docs: "Use Button for explicit commands, links, and action affordances. The Yew wrapper supports semantic button states plus link rendering for navigation-style actions.",
        component_name: "Button",
        class_name: "btn",
        api_kind: ApiKind::Button,
    },
    ComponentSpec {
        slug: "file-upload",
        name: "File Upload",
        category: "Actions",
        description: "Drag-and-drop file uploader.",
        docs: "Use File Upload to frame file selection, upload drop zones, and selected-file summaries inside form flows.",
        component_name: "FileUpload",
        class_name: "file-upload",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "toggle",
        name: "Toggle",
        category: "Actions",
        description: "Toggle button controls.",
        docs: "Use Toggle for binary tool states where the pressed state behaves like an action button rather than a form switch.",
        component_name: "Toggle",
        class_name: "toggle-group",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "avatar",
        name: "Avatar",
        category: "Data Display",
        description: "User profile pictures.",
        docs: "Use Avatar to represent people, teams, or entities in lists, cards, and collaborative surfaces.",
        component_name: "Avatar",
        class_name: "avatar",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "badge",
        name: "Badge",
        category: "Data Display",
        description: "Status indicators.",
        docs: "Use Badge for compact counts, labels, statuses, and short metadata attached to nearby content.",
        component_name: "Badge",
        class_name: "badge",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "card",
        name: "Card",
        category: "Data Display",
        description: "Content containers.",
        docs: "Use Card to group related content with an optional title and a consistent body surface.",
        component_name: "Card",
        class_name: "card",
        api_kind: ApiKind::Card,
    },
    ComponentSpec {
        slug: "chip",
        name: "Chip",
        category: "Data Display",
        description: "Compact tags.",
        docs: "Use Chip for tags, filters, selected entities, and compact attribute values.",
        component_name: "Chip",
        class_name: "chip",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "code-block",
        name: "Code Block",
        category: "Data Display",
        description: "Styled code containers.",
        docs: "Use Code Block for readable code samples, terminal output, or configuration snippets.",
        component_name: "CodeBlock",
        class_name: "code-block",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "code-engine",
        name: "Code Engine",
        category: "Data Entry",
        description: "Pure Rust code editor foundation.",
        docs: "Use Code Engine when users need line-aware source editing through the pure Rust yew-code-engine crate.",
        component_name: "CodeEditor",
        class_name: "code-engine",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "collapse",
        name: "Collapse",
        category: "Data Display",
        description: "Collapsible content.",
        docs: "Use Collapse when a single content region should reveal details while preserving page context.",
        component_name: "Collapse",
        class_name: "collapse",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "list",
        name: "List",
        category: "Data Display",
        description: "Vertical item lists.",
        docs: "Use List for repeated rows, menus, timeline feeds, and other vertically scanned content.",
        component_name: "List",
        class_name: "list",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "markdown-body",
        name: "Markdown Body",
        category: "Data Display",
        description: "GitHub-style markdown typography.",
        docs: "Use Markdown Body to scope prose, generated markdown, and rich text to a readable content style.",
        component_name: "MarkdownBody",
        class_name: "markdown-body",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "dm-markdown",
        name: "Dm Markdown",
        category: "Data Display",
        description: "Markdown renderer with Duskmoon typography.",
        docs: "Use Dm Markdown to render markdown source into the same readable style as Markdown Body.",
        component_name: "DmMarkdown",
        class_name: "markdown-body",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "table",
        name: "Table",
        category: "Data Display",
        description: "Data tables.",
        docs: "Use Table for structured rows and columns that need scanning, comparison, and status display.",
        component_name: "Table",
        class_name: "table",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "timeline",
        name: "Timeline",
        category: "Data Display",
        description: "Chronological events.",
        docs: "Use Timeline for ordered activity, history, deployment, or progress events.",
        component_name: "Timeline",
        class_name: "timeline",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "autocomplete",
        name: "Autocomplete",
        category: "Data Entry",
        description: "Search with suggestions.",
        docs: "Use Autocomplete where typed input should narrow a known list of options.",
        component_name: "Autocomplete",
        class_name: "autocomplete",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "cascader",
        name: "Cascader",
        category: "Data Entry",
        description: "Multi-level cascading selection.",
        docs: "Use Cascader for hierarchical choices where each level depends on the previous selection.",
        component_name: "Cascader",
        class_name: "cascader",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "checkbox",
        name: "Checkbox",
        category: "Data Entry",
        description: "Multiple selection checkboxes.",
        docs: "Use Checkbox when users can select any number of independent options.",
        component_name: "Checkbox",
        class_name: "checkbox",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "datepicker",
        name: "Date Picker",
        category: "Data Entry",
        description: "Calendar selection.",
        docs: "Use Date Picker when a date should be selected with calendar context rather than free text.",
        component_name: "DatePicker",
        class_name: "datepicker",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "form",
        name: "Form",
        category: "Data Entry",
        description: "Complete form examples.",
        docs: "Use Form as a structural wrapper for related labels, controls, validation, and submit actions.",
        component_name: "Form",
        class_name: "form",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "form-group",
        name: "Form Group",
        category: "Data Entry",
        description: "Form layout utilities.",
        docs: "Use Form Group to arrange related inputs, helper text, and validation messages.",
        component_name: "FormGroup",
        class_name: "form-group",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "input",
        name: "Input",
        category: "Data Entry",
        description: "Text input fields.",
        docs: "Use Input for single-line text entry or readonly display in form contexts.",
        component_name: "Input",
        class_name: "input",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "markdown-input",
        name: "Markdown Input",
        category: "Data Entry",
        description: "Markdown textarea with preview.",
        docs: "Use Markdown Input when users need to write markdown and quickly inspect the rendered output before submitting.",
        component_name: "MarkdownInput",
        class_name: "markdown-input",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "multi-select",
        name: "Multi-Select",
        category: "Data Entry",
        description: "Multiple selection dropdown.",
        docs: "Use Multi-Select when several options can be chosen from a bounded set.",
        component_name: "MultiSelect",
        class_name: "multi-select",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "otp-input",
        name: "OTP Input",
        category: "Data Entry",
        description: "Verification code input.",
        docs: "Use OTP Input for short verification codes split across predictable character slots.",
        component_name: "OtpInput",
        class_name: "otp-input",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "pin-input",
        name: "PIN Input",
        category: "Data Entry",
        description: "Secure PIN entry.",
        docs: "Use PIN Input for numeric secret entry where fixed-length input improves clarity.",
        component_name: "PinInput",
        class_name: "pin-input",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "radio",
        name: "Radio",
        category: "Data Entry",
        description: "Single selection radio buttons.",
        docs: "Use Radio when exactly one option should be selected from a visible group.",
        component_name: "Radio",
        class_name: "radio",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "rating",
        name: "Rating",
        category: "Data Entry",
        description: "Star/heart ratings.",
        docs: "Use Rating to capture or display small ordinal satisfaction or quality values.",
        component_name: "Rating",
        class_name: "rating",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "segment-control",
        name: "Segment Control",
        category: "Data Entry",
        description: "Segmented button toggle.",
        docs: "Use Segment Control for mutually exclusive modes with a compact horizontal footprint.",
        component_name: "SegmentControl",
        class_name: "segment-control",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "select",
        name: "Select",
        category: "Data Entry",
        description: "Dropdown selection.",
        docs: "Use Select when users choose one option from a menu-like list.",
        component_name: "Select",
        class_name: "select",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "slider",
        name: "Slider",
        category: "Data Entry",
        description: "Range selector.",
        docs: "Use Slider for approximate numeric ranges where dragging is faster than typing.",
        component_name: "Slider",
        class_name: "slider",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "switch",
        name: "Switch",
        category: "Data Entry",
        description: "Toggle controls.",
        docs: "Use Switch for persistent on/off preferences and settings.",
        component_name: "Switch",
        class_name: "switch",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "textarea",
        name: "Textarea",
        category: "Data Entry",
        description: "Multi-line text input.",
        docs: "Use Textarea for longer freeform text, notes, descriptions, and comments.",
        component_name: "Textarea",
        class_name: "textarea",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "time-input",
        name: "Time Input",
        category: "Data Entry",
        description: "Time selection.",
        docs: "Use Time Input when users need to enter or confirm a clock time.",
        component_name: "TimeInput",
        class_name: "time-input",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "tree-select",
        name: "Tree Select",
        category: "Data Entry",
        description: "Hierarchical dropdown.",
        docs: "Use Tree Select for hierarchical options that still need dropdown-like compactness.",
        component_name: "TreeSelect",
        class_name: "tree-select",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "alert",
        name: "Alert",
        category: "Feedback",
        description: "Important messages.",
        docs: "Use Alert for prominent inline feedback that should remain visible until the surrounding context changes.",
        component_name: "Alert",
        class_name: "alert",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "dialog",
        name: "Dialog",
        category: "Feedback",
        description: "Modal dialogs.",
        docs: "Use Dialog for focused confirmations, choices, or short blocking tasks.",
        component_name: "Dialog",
        class_name: "dialog",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "modal",
        name: "Modal",
        category: "Feedback",
        description: "Full-featured overlays.",
        docs: "Use Modal for overlay content that needs more structure than a short dialog.",
        component_name: "Modal",
        class_name: "modal",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "progress",
        name: "Progress",
        category: "Feedback",
        description: "Loading indicators.",
        docs: "Use Progress to show bounded or unbounded work that is still running.",
        component_name: "Progress",
        class_name: "progress",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "skeleton",
        name: "Skeleton",
        category: "Feedback",
        description: "Loading placeholders.",
        docs: "Use Skeleton to reserve layout while data or media is loading.",
        component_name: "Skeleton",
        class_name: "skeleton",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "snackbar",
        name: "Snackbar",
        category: "Feedback",
        description: "Brief messages.",
        docs: "Use Snackbar for low-interruption status messages tied to a recent action.",
        component_name: "Snackbar",
        class_name: "snackbar",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "toast",
        name: "Toast",
        category: "Feedback",
        description: "Toast notifications.",
        docs: "Use Toast for transient notifications that do not block the current workflow.",
        component_name: "Toast",
        class_name: "toast",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "tooltip",
        name: "Tooltip",
        category: "Feedback",
        description: "Contextual information.",
        docs: "Use Tooltip for brief contextual help attached to a focused or hovered target.",
        component_name: "Tooltip",
        class_name: "tooltip",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "appbar",
        name: "App Bar",
        category: "Layout",
        description: "Action bars.",
        docs: "Use App Bar to frame page-level navigation, titles, and persistent actions.",
        component_name: "AppBar",
        class_name: "appbar",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "divider",
        name: "Divider",
        category: "Layout",
        description: "Visual separators.",
        docs: "Use Divider to separate related groups without adding a heavy container.",
        component_name: "Divider",
        class_name: "divider",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "grid",
        name: "Grid",
        category: "Layout",
        description: "Auto-fill/auto-fit responsive grids.",
        docs: "Use Grid for responsive track layouts that need predictable column presets and gap control.",
        component_name: "Grid",
        class_name: "grid",
        api_kind: ApiKind::Grid,
    },
    ComponentSpec {
        slug: "bottom-navigation",
        name: "Bottom Navigation",
        category: "Navigation",
        description: "Mobile bottom nav.",
        docs: "Use Bottom Navigation for mobile-primary destinations that should stay close to the thumb zone.",
        component_name: "BottomNavigation",
        class_name: "bottom-navigation",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "breadcrumbs",
        name: "Breadcrumbs",
        category: "Navigation",
        description: "Hierarchical navigation.",
        docs: "Use Breadcrumbs to show the current page position inside a hierarchy.",
        component_name: "Breadcrumbs",
        class_name: "breadcrumbs",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "circle-menu",
        name: "Circle Menu",
        category: "Navigation",
        description: "Radial circular navigation.",
        docs: "Use Circle Menu for compact radial actions where spatial placement helps recognition.",
        component_name: "CircleMenu",
        class_name: "circle-menu",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "drawer",
        name: "Drawer",
        category: "Navigation",
        description: "Side navigation.",
        docs: "Use Drawer for secondary navigation, filters, or contextual tools that slide from an edge.",
        component_name: "Drawer",
        class_name: "drawer",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "menu",
        name: "Menu",
        category: "Navigation",
        description: "Dropdown menus.",
        docs: "Use Menu for compact command lists, contextual choices, and short navigation groups.",
        component_name: "Menu",
        class_name: "menu",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "navbar",
        name: "Navbar",
        category: "Navigation",
        description: "Primary navigation.",
        docs: "Use Navbar for persistent top-level destinations and identity.",
        component_name: "Navbar",
        class_name: "navbar",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "nested-menu",
        name: "Nested Menu",
        category: "Navigation",
        description: "Collapsible sidebar navigation.",
        docs: "Use Nested Menu for deeper navigation groups that need expandable hierarchy.",
        component_name: "NestedMenu",
        class_name: "nested-menu",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "pagination",
        name: "Pagination",
        category: "Navigation",
        description: "Page navigation.",
        docs: "Use Pagination to move between pages or chunks of ordered records.",
        component_name: "Pagination",
        class_name: "pagination",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "stepper",
        name: "Stepper",
        category: "Navigation",
        description: "Multi-step guide.",
        docs: "Use Stepper to show progress through a fixed sequence of workflow steps.",
        component_name: "Stepper",
        class_name: "stepper",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "tabs",
        name: "Tabs",
        category: "Navigation",
        description: "Tab navigation.",
        docs: "Use Tabs to switch between sibling views at the same hierarchy level.",
        component_name: "Tabs",
        class_name: "tabs",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "accordion",
        name: "Accordion",
        category: "Surfaces",
        description: "Expandable panels.",
        docs: "Use Accordion for stacked sections where users open one or more details inline.",
        component_name: "Accordion",
        class_name: "accordion",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "bottom-sheet",
        name: "Bottom Sheet",
        category: "Surfaces",
        description: "Mobile panels.",
        docs: "Use Bottom Sheet for mobile-first task panels that rise from the bottom edge.",
        component_name: "BottomSheet",
        class_name: "bottomsheet",
        api_kind: ApiKind::Standard,
    },
    ComponentSpec {
        slug: "popover",
        name: "Popover",
        category: "Surfaces",
        description: "Contextual overlays.",
        docs: "Use Popover for anchored contextual content that should remain lighter than a modal.",
        component_name: "Popover",
        class_name: "popover",
        api_kind: ApiKind::Standard,
    },
];

pub fn component_by_slug(slug: &str) -> Option<&'static ComponentSpec> {
    COMPONENTS.iter().find(|component| component.slug == slug)
}
